"""Verify Tier-2's TL claim in the KINK variables, independently.

For 156/198 a wall-free gap has basis the descending states 1^k 0^{l-k}.  Write
|k> for the kink position.  Then e_i should be RANK ONE on span{|i>,|i+1>} with
v_i ~ |i> - (1+sqrt2)|i+1>, adjacent overlaps |<v_i|v_{i+1}>|^2 = 1/8, and the
TL chain should be arbitrarily long.

Built here from the SITE picture (project the full e_i onto the kink subspace),
so it is an independent check and not a re-implementation of their algebra.
"""
import sys
import numpy as np

sys.path.insert(0, "/home/mkmullenbach/Dokumente/Projects/QCA Simulations/"
                   "Claude Sector Analysis/.claude/worktrees/tier1-analysis/code")
from qca_fragmentation.core import rules as R

SQ2 = np.sqrt(2.0)
H = (1 / SQ2) * np.array([[1.0, 1.0], [1.0, -1.0]])
w, V = np.linalg.eigh(H)
hm = V[:, np.argmin(w)] / np.linalg.norm(V[:, np.argmin(w)])
Pm = np.outer(hm, hm)
PROJ = {0: np.array([[1.0, 0.0], [0.0, 0.0]]),
        1: np.array([[0.0, 0.0], [0.0, 1.0]])}


def v_context(rule):
    t = R.wolfram_to_tuple(rule)
    i = t.index("V")
    return (i >> 1) & 1, i & 1


def site_op(op, i, N):
    out = np.array([[1.0]])
    for k in range(N):
        out = np.kron(out, op if k == i else np.eye(2))
    return out


def e_op(i, N, m, n):
    return site_op(PROJ[m], i - 1, N) @ site_op(Pm, i, N) @ site_op(PROJ[n], i + 1, N)


def kink_states(N, m, n):
    """The descending family: m* repeated then n* repeated.  Site 0 leftmost."""
    out = []
    for k in range(N + 1):
        x = 0
        for s in range(N):
            bit = m if s < k else n
            if bit:
                x |= 1 << (N - 1 - s)      # site_op puts site 0 in the MSB
        out.append(x)
    return sorted(set(out))


def check(rule, N):
    m, n = v_context(rule)
    tau = abs(hm[m]) ** 2 * abs(hm[n]) ** 2
    S = kink_states(N, m, n)
    P = np.zeros((len(S), 1 << N))
    for a, x in enumerate(S):
        P[a, x] = 1.0
    es = {i: e_op(i, N, m, n) for i in range(1, N - 1)}
    # closure of the kink family under the generators
    leak = max(float(np.abs(es[i] @ P.T - P.T @ (P @ es[i] @ P.T)).max())
               for i in es)
    er = {i: P @ es[i] @ P.T for i in es}
    alive = [i for i in sorted(er) if np.abs(er[i]).max() > 1e-12]
    ranks = [int(np.linalg.matrix_rank(er[i], tol=1e-10)) for i in alive]
    # TL relation among adjacent live generators
    worst, npairs = 0.0, 0
    for i in alive:
        for j in (i - 1, i + 1):
            if j in alive:
                npairs += 1
                worst = max(worst, float(np.abs(er[i] @ er[j] @ er[i]
                                                - tau * er[i]).max()))
    # far commutation
    farc = max((float(np.abs(er[i] @ er[j] - er[j] @ er[i]).max())
                for i in alive for j in alive if j >= i + 2), default=0.0)
    # adjacent overlaps of the rank-one vectors, and their amplitude ratio
    ov, ratio = [], []
    for i in alive:
        wv, Vv = np.linalg.eigh(er[i])
        v = Vv[:, np.argmax(wv)]
        nz = np.nonzero(np.abs(v) > 1e-9)[0]
        if len(nz) == 2:
            ratio.append(v[nz[1]] / v[nz[0]])
        if i + 1 in alive:
            wv2, Vv2 = np.linalg.eigh(er[i + 1])
            v2 = Vv2[:, np.argmax(wv2)]
            ov.append(abs(np.vdot(v, v2)) ** 2)
    # dimension of the algebra generated by the live e_i
    basis = [np.eye(len(S))] + [er[i] for i in alive]
    changed = True
    while changed and len(basis) < 4000:
        M = np.array([b.reshape(-1) for b in basis])
        r0 = np.linalg.matrix_rank(M, tol=1e-9)
        new = []
        for i in alive:
            for b in basis:
                new.append(er[i] @ b)
        M2 = np.array([b.reshape(-1) for b in basis + new])
        r1 = np.linalg.matrix_rank(M2, tol=1e-9)
        changed = r1 > r0
        if changed:
            u, s, vh = np.linalg.svd(M2, full_matrices=False)
            k = int(np.sum(s > 1e-9 * s[0]))
            basis = [vh[t].reshape(len(S), len(S)) for t in range(k)]
    dimA = np.linalg.matrix_rank(
        np.array([b.reshape(-1) for b in basis]), tol=1e-9)
    d = len(S)
    return dict(N=N, d=d, gens=len(alive), ranks=sorted(set(ranks)), leak=leak,
                tl=worst, farc=farc, npairs=npairs,
                ov=(min(ov), max(ov)) if ov else None,
                ratio=(min(np.real(ratio)), max(np.real(ratio))) if ratio else None,
                dimA=int(dimA), pred=(d - 1) ** 2 + 1)


if __name__ == "__main__":
    for rule in (156, 198):
        word = "".join(R.wolfram_to_tuple(rule))
        print(f"\n=== W{rule} ({word}) on the kink module, tau = 1/8, "
              f"delta = 2 sqrt2 = {2*SQ2:.6f} ===")
        print(f"{'N':>3} {'dim':>4} {'gens':>5} {'ranks':>8} {'closure':>9} "
              f"{'TL err':>9} {'[e,e] far':>9} {'|<v_i|v_i+1>|^2':>16} "
              f"{'ratio':>10} {'dim A':>6} {'(d-1)^2+1':>10}")
        for N in (5, 6, 7, 8, 9, 10):
            z = check(rule, N)
            ovs = f"{z['ov'][0]:.6f}" if z["ov"] else "-"
            rat = f"{z['ratio'][0]:.6f}" if z["ratio"] else "-"
            print(f"{z['N']:>3} {z['d']:>4} {z['gens']:>5} {str(z['ranks']):>8} "
                  f"{z['leak']:>9.1e} {z['tl']:>9.1e} {z['farc']:>9.1e} "
                  f"{ovs:>16} {rat:>10} {z['dimA']:>6} {z['pred']:>10}")
    print(f"\n-(1+sqrt2) = {-(1+SQ2):.6f}    1/8 = 0.125")
