"""Figure and tables for R30: the sector-size distribution.

(a) the exact size histogram on the ring against the predicted log-normal,
(b) the free energy tau(s) and its Legendre transform g(alpha), with the four
    landmarks alpha=0, alpha_typ, alpha_state, alpha_max marked, and
(c) the finite-size offsets, which vanish on the ring and are rule-dependent --
    including positive for W201 -- on the chain.
"""
from __future__ import annotations

import math
import os
from typing import Dict, List, Optional, Sequence

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from . import sector_sizes as S

HERE = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
FIGURES = os.path.join(os.path.dirname(HERE), "figures")
TABLES = os.path.join(os.path.dirname(HERE), "reports", "tex")

COLOR = {156: "#1f4e9c", 198: "#6fa8dc", 108: "#b03030", 201: "#e08b3a"}


def _style(ax):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(labelsize=8)


def figure(out: Optional[str] = None, N_hist: int = 60, N_off: int = 160):
    out = out or os.path.join(FIGURES, "fig_sector_sizes")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    fig, axes = plt.subplots(1, 3, figsize=(13.0, 3.7))

    # (a) the log-normal law, on the ring where there is no boundary offset.
    # The exact distribution is a COMB -- sizes live on the multiplicative
    # semigroup generated by the gap kernel -- so the honest comparison is a
    # binned density, not multiplicity per achievable size.
    ax = axes[0]
    _style(ax)
    for rule in (156, 108):
        h = S.hist(rule, N_hist, "pbc")
        n = float(sum(h.values()))
        u = np.array([math.log(k) / N_hist for k in h])
        w = np.array([h[k] for k in h], dtype=float) / n
        edges = np.linspace(0.0, 0.55, 56)
        dens, _ = np.histogram(u, bins=edges, weights=w)
        dens /= (edges[1] - edges[0])
        ctr = 0.5 * (edges[1:] + edges[:-1])
        ax.step(ctr, dens, where="mid", lw=1.3, color=COLOR[rule],
                label=f"$W_{{{rule}}}$ exact, $N={N_hist}$")
        a0, v0 = S.tau_derivatives(rule, 0.0)
        xs = np.linspace(0, 0.55, 500)
        g = (math.sqrt(N_hist / (2 * math.pi * v0))
             * np.exp(-N_hist * (xs - a0) ** 2 / (2 * v0)))
        ax.plot(xs, g, "--", lw=1.2, color="#333333", alpha=0.8,
                label=(r"$\mathcal{N}(\alpha_{\rm typ}N,\sigma^2N)$"
                       if rule == 156 else None))
        ax.axvline(S.alpha_max(rule), color=COLOR[rule], ls=":", lw=0.9)
    ax.annotate(r"$\alpha_{\max}$", (S.alpha_max(156) + 0.005, 7.0),
                fontsize=6.8, color=COLOR[156])
    ax.annotate(r"$\alpha_{\max}$", (S.alpha_max(108) + 0.005, 7.0),
                fontsize=6.8, color=COLOR[108])
    ax.set_xlim(0, 0.55)
    ax.set_xlabel(r"$\alpha=\ln|\mathcal{K}| / N$")
    ax.set_ylabel("density of sectors")
    ax.set_title("(a)  the sizes are log-normal", fontsize=9.5)
    ax.legend(fontsize=6.6, frameon=False, loc="upper right")

    # (b) tau(s) and the large-deviation spectrum
    ax = axes[1]
    _style(ax)
    for rule in (156, 108):
        smax = 150.0 if S.FAMILY[rule] == "parabolic" else 12.0
        ss = list(np.linspace(-8.0, 3.0, 23)) + \
            list(np.exp(np.linspace(math.log(3.2), math.log(smax), 12)))
        sp = S.spectrum(rule, ss)
        al = [p["alpha"] for p in sp]
        gg = [p["g"] for p in sp]
        ax.plot(al, gg, "-", lw=1.6, color=COLOR[rule],
                label=f"$W_{{{rule}}}$")
        a0, _ = S.tau_derivatives(rule, 0.0)
        a1, _ = S.tau_derivatives(rule, 1.0)
        ax.plot([a0], [math.log(S.lambda_s(rule, 0.0))], "o", ms=5,
                color=COLOR[rule])
        ax.plot([a1], [math.log(2) - a1], "s", ms=4.5, color=COLOR[rule])
        ax.plot([S.alpha_max(rule)], [0.0], "^", ms=5, color=COLOR[rule])
    ax.axhline(0, color="#888888", lw=0.7)
    ax.annotate("typical sector ($s=0$)", (0.075, 0.575), fontsize=6.6,
                color="#333333")
    ax.annotate("typical STATE's sector ($s=1$)", (0.21, 0.30), fontsize=6.6,
                color="#333333")
    ax.annotate(r"$\alpha_{\max}$: one sector", (0.30, 0.035), fontsize=6.6,
                color="#333333")
    ax.set_xlabel(r"$\alpha = \ln|\mathcal{K}|/N$")
    ax.set_ylabel(r"$g(\alpha)$:  $\#$sectors $= e^{N g(\alpha)}$")
    ax.set_title(r"(b)  the spectrum, $g=$ Legendre transform of "
                 r"$\ln\lambda_s$", fontsize=9.5)
    ax.legend(fontsize=7.0, frameon=False, loc="upper left")

    # (c) the finite-size offset
    ax = axes[2]
    _style(ax)
    Ns = [n for n in range(12, N_off + 1, 4)]
    for rule in S.RULES:
        a0, _ = S.tau_derivatives(rule, 0.0)
        for bc, ls in (("obc0", "-"), ("pbc", "--")):
            ys = [S.cumulants(rule, n, bc)["mean"] - a0 * n for n in Ns]
            ax.plot(Ns, ys, ls, lw=1.3, color=COLOR[rule],
                    label=f"$W_{{{rule}}}$ {bc}")
    ax.axhline(0, color="#888888", lw=0.7)
    ax.set_xlabel("$N$")
    ax.set_ylabel(r"$\langle\ln|\mathcal{K}|\rangle - \alpha_0 N$")
    ax.set_title("(c)  the ring has no offset; the chain's is rule-dependent",
                 fontsize=9.5)
    ax.legend(fontsize=6.0, frameon=False, ncol=2, loc="center right")

    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(f"{out}.{ext}", dpi=200, bbox_inches="tight")
    plt.close(fig)
    return out


def figure_multiplicity(out: Optional[str] = None, N_meas: int = 16,
                        N_big: int = 400):
    """n_N(sigma): how many sectors have exactly size sigma.

    (a) the measured histogram (union-find on the 2^N flip graph) against the
        renewal formula, at a size where brute force is still possible;
    (b) the parabolic law -- a POLYNOMIAL in N of degree Omega(sigma)+1, so the
        census reads off the prime factorisation of sigma;
    (c) the hyperbolic law -- A(sigma) N^{m} phi^N, exponential, because the
        1-gap is degenerate there (g in {0,2,3}) and x+x^3+x^4 = 1 at 1/phi.
    """
    out = out or os.path.join(FIGURES, "fig_sector_multiplicity")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    fig, axes = plt.subplots(2, 2, figsize=(11.0, 7.0))
    axes = axes.ravel()

    # (a) formula vs measurement, obc0
    ax = axes[0]
    _style(ax)
    for rule, off in ((156, -0.22), (108, +0.22)):
        meas = S.hist_bruteforce(rule, N_meas, "obc0")
        sig = sorted(meas)
        ax.bar(np.array(sig) + off, [meas[s] for s in sig], 0.44,
               color=COLOR[rule], label=f"$W_{{{rule}}}$ measured "
                                        f"($2^{{N}}$ flip graph)")
        form = [S.multiplicity(rule, N_meas, "obc0", s) for s in sig]
        ax.plot(np.array(sig) + off, form, "k_", ms=6, mew=1.1,
                label="renewal formula" if rule == 156 else None)
        assert form == [meas[s] for s in sig]
    ax.set_yscale("log")
    ax.set_xlim(0, 40)
    ax.set_xlabel(r"sector size $\sigma$")
    ax.set_ylabel(r"$n_N(\sigma)$")
    ax.set_title(rf"(a)  obc0, $N={N_meas}$: the gaps in the $W_{{108}}$ comb "
                 r"are the non-Fibonacci $\sigma$", fontsize=8.6)
    ax.legend(fontsize=6.2, frameon=False, loc="upper right")

    # (b) the ring, and its parity selection rule
    ax = axes[1]
    _style(ax)
    for N, off, sty in ((N_meas, -0.22, dict(color=COLOR[156])),
                        (N_meas + 1, +0.22, dict(color="#9ec2f0"))):
        meas = S.hist_bruteforce(156, N, "pbc")
        sig = sorted(meas)
        ax.bar(np.array(sig) + off, [meas[s] for s in sig], 0.44,
               label=f"$W_{{156}}$ measured, $N={N}$", **sty)
        form = [S.multiplicity(156, N, "pbc", s) for s in sig]
        ax.plot(np.array(sig) + off, form, "k_", ms=6, mew=1.1,
                label="renewal formula" if N == N_meas else None)
        assert form == [meas[s] for s in sig]
    ax.set_yscale("log")
    ax.set_xlim(0, 26)
    ax.set_xlabel(r"sector size $\sigma$")
    ax.set_ylabel(r"$n_N(\sigma)$")
    ax.set_title(r"(b)  pbc: consecutive $N$ populate DISJOINT sizes "
                 r"($N\equiv\mathrm{sopfr}+\Omega$)", fontsize=8.6)
    ax.legend(fontsize=6.2, frameon=False, loc="upper right")

    # (c) the parabolic polynomial law
    ax = axes[2]
    _style(ax)
    Ns = [50, 100, 200, 400, 800, 1600]
    for sig, mark in ((2, "o"), (4, "s"), (6, "^"), (12, "v"), (30, "D")):
        ys = [S.multiplicity(156, n, "obc0", sig) for n in Ns]
        ax.plot(Ns, ys, mark + "-", ms=3.4, lw=1.0,
                label=fr"$\sigma={sig}$, $\Omega={S.omega(sig)}$")
        ax.plot(Ns, [S.multiplicity_asymptotic(156, n, "obc0", sig)
                     for n in Ns], "k--", lw=0.8,
                label="closed form" if sig == 2 else None)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("$N$")
    ax.set_ylabel(r"$n_N(\sigma)$")
    ax.set_title(r"(c)  $W_{156}/W_{198}$: $n_N(\sigma)\simeq P(\sigma)"
                 r"(N/2)^{\Omega+1}/(\Omega+1)!$", fontsize=9.0)
    ax.legend(fontsize=6.2, frameon=False, loc="upper left")

    # (d) the hyperbolic exponential law
    ax = axes[3]
    _style(ax)
    phi = (1 + math.sqrt(5)) / 2
    Ns = [60, 100, 150, 220, 320, 460]
    for sig, mark in ((1, "o"), (2, "s"), (4, "^"), (8, "v"), (16, "D")):
        m = S.multiplicity_degree(108, sig)
        ys = [S.multiplicity(108, n, "obc0", sig) / phi ** n for n in Ns]
        ax.plot(Ns, ys, mark, ms=3.8, color=COLOR[108],
                alpha=0.4 + 0.14 * m, label=fr"$\sigma={sig}$, $m={m}$")
        A = ys[-1] / Ns[-1] ** m                  # the residue, read off at N_max
        ax.plot(Ns, [A * n ** m for n in Ns], "-", lw=0.9, color="#666666",
                label=r"$A(\sigma)N^{m}$" if sig == 1 else None)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("$N$")
    ax.set_ylabel(r"$n_N(\sigma)\,\varphi^{-N}$")
    ax.set_title(r"(d)  $W_{108}/W_{201}$: $n_N(\sigma)\simeq A(\sigma)N^{m}"
                 r"\varphi^{N}$", fontsize=9.0)
    ax.legend(fontsize=6.2, frameon=False, loc="upper left")

    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(f"{out}.{ext}", dpi=200, bbox_inches="tight")
    plt.close(fig)
    return out


# --- tables -------------------------------------------------------------------

def _tex(path: str, body: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(body)


def write_tables(outdir: Optional[str] = None,
                 Ns: Sequence[int] = (6, 8, 10, 12, 14, 16, 18, 20)):
    outdir = outdir or TABLES

    # 1. the kernel table: one 2x2 matrix per rule
    rows = []
    for rule in S.RULES:
        a, b = S.WALL_WORD[rule]
        m0 = S.wall_matrices(rule)[0]
        K = "F(g-1)" if S.FAMILY[rule] == "hyperbolic" else "g"
        L = {156: "1", 198: "g", 108: "F(g-1)", 201: "F(g)"}[rule]
        R = {156: "g", 198: "1", 108: "F(g-1)", 201: "F(g)"}[rule]
        rows.append(
            r"$W_{%d}$ & \texttt{%d%d} & $\begin{psmallmatrix}%d&%d\\%d&%d"
            r"\end{psmallmatrix}$ & %s & $%s$ & $%s$ & $%s$ \\"
            % (rule, a, b, m0[0][0], m0[0][1], m0[1][0], m0[1][1],
               S.FAMILY[rule], K, L, R))
    _tex(os.path.join(outdir, "tab_r30_kernels.tex"),
         "\\begin{tabular}{lllllll}\n\\toprule\nrule & word & $M_0$ & type & "
         "$K(g)$ & $L(g)$ & $R(g)$ \\\\\n\\midrule\n"
         + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")

    # 2. the exact census, both bc
    for bc in ("obc0", "pbc"):
        rows = []
        for rule in S.RULES:
            cells = []
            for N in Ns:
                h = S.hist(rule, N, bc)
                cells.append(r"%d/%d/%d" % (sum(h.values()), max(h),
                                            h.get(1, 0)))
            rows.append(r"$W_{%d}$ & %s \\" % (rule, " & ".join(cells)))
        _tex(os.path.join(outdir, f"tab_r30_census_{bc}.tex"),
             "\\begin{tabular}{l%s}\n\\toprule\nrule & %s \\\\\n\\midrule\n"
             % ("l" * len(Ns), " & ".join("$N=%d$" % n for n in Ns))
             + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")

    # 3. the asymptotic constants
    rows = []
    for rule in S.RULES:
        p = S.lognormal_params(rule)
        o = S.offsets(rule, "obc0", 160)
        rows.append(
            r"$W_{%d}$ & %.6f & %.6f & %.6f & %.6f & %.6f & $%+.6f$ & "
            r"$%+.6f$ \\"
            % (rule, p["lambda_0"], p["alpha_typ"], p["sigma2"],
               p["alpha_state"], p["alpha_max"], o["c1"], o["c2"]))
    _tex(os.path.join(outdir, "tab_r30_asymptotics.tex"),
         "\\begin{tabular}{llllllll}\n\\toprule\nrule & $\\lambda_0$ & "
         "$\\alpha_{\\rm typ}$ & $\\sigma^2$ & $\\alpha_{\\rm state}$ & "
         "$\\alpha_{\\max}$ & $c_1$ (\\texttt{obc0}) & $c_2$ "
         "(\\texttt{obc0}) \\\\\n\\midrule\n"
         + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")

    # 4. lambda_s at integer s, with the minimal polynomials Tier-2 reports
    minpoly = {(156, 0): r"\lambda^2-\lambda-1",
               (108, 0): r"\lambda^3-2\lambda^2+\lambda-1",
               (156, 1): r"\lambda-2", (108, 1): r"\lambda-2",
               (156, 2): r"\lambda^3-3\lambda^2+2\lambda-2",
               (108, 2): r"\lambda^2-2\lambda-2",
               (156, 3): r"\lambda^3-4\lambda^2+5\lambda-8",
               (108, 3): r"\lambda^3-4\lambda^2-3\lambda+8"}
    rows = []
    for rule, name in ((156, "156/198"), (108, "108/201")):
        for s in (0, 1, 2, 3):
            rows.append(r"%s & %d & $%s$ & %.12f \\"
                        % (name if s == 0 else "", s, minpoly[(rule, s)],
                           S.lambda_s(rule, float(s), dps=40)))
    _tex(os.path.join(outdir, "tab_r30_lambda.tex"),
         "\\begin{tabular}{llll}\n\\toprule\nfamily & $s$ & minimal polynomial "
         "& $\\lambda_s$ \\\\\n\\midrule\n"
         + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    return outdir


def main(argv: Optional[List[str]] = None) -> int:
    out = figure()
    figure_multiplicity()
    write_tables()
    print("wrote", out + ".pdf", "fig_sector_multiplicity.pdf and the R30 tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
